<?php

namespace vandash\config;

$_ENV['USER_ID']='USER_ID';
$_ENV['TASK_ID']='TASK_ID';
$_ENV['TASK_TITLE']='TASK_TITLE';
$_ENV['TASK_DATE']='TASK_DATE';
$_ENV['DATE_DUE']='DATE_DUE';
$_ENV['TASK_TYPE']='TASK_TYPE';
$_ENV['REFERENCE']='REFERENCE';
$_ENV['PERC_COMPLETE']='PERC_COMPLETE';
$_ENV['DATE_COMPLTED']='DATE_COMPLTED';
$_ENV['TASK_DESC']='TASK_DESC';
$_ENV['TASK_NOTES']='TASK_NOTES';
$_ENV['TASK_STATUS']='TASK_STATUS';
$_ENV['UPDATE_DATE']='UPDATE_DATE';
$_ENV['ASCENDING']='ASCENDING';
$_ENV['DESCENDING']='DESCENDING';
$_ENV['NOTE_ID']='NOTE_ID';
$_ENV['NOTE_TITLE']='NOTE_TITLE';
$_ENV['NOTE_DATE']='NOTE_DATE';
$_ENV['NOTE_TEXT']='NOTE_TEXT';
$_ENV['USER_ID']='USER_ID';
$_ENV['USERNAME']='USERNAME';
$_ENV['PASSWORD']='PASSWORD';
$_ENV['USER_EMAIL']='USER_EMAIL';
$_ENV['DATE_CREATED']='DATE_CREATED';

$_ENV['DEFAULT_COMPARISON']='';
$_ENV['STRING_COMPARISON']='strcmp';
$_ENV['INTEGER_COMPARISON']='intcmp';
$_ENV['NUMERIC_COMPARISON']='numcmp';

